# Generated by Django 5.2.7 on 2025-10-30 15:41

import server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.category_icon_upload_path
            ),
        ),
    ]
