# Generated by Django 5.2.7 on 2025-11-06 17:01

import server.models
import server.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_chanel_banner_chanel_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chanel",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="chanel",
            name="icon",
        ),
        migrations.AddField(
            model_name="server",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to=server.models.server_banner_upload_path
            ),
        ),
        migrations.AddField(
            model_name="server",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_icon_upload_path,
                validators=[server.validator.validate_icon_image_size],
            ),
        ),
    ]
